name: Beta Release

on:
  push:
    tags:
      - 'v*-beta*'   # z.B. v1.1.0-beta, v1.2.0-beta.1

jobs:
  publish-beta:
    name: Publish @cvrocket/core (beta)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies (workspace root)
        run: pnpm install --frozen-lockfile

      - name: Build package
        working-directory: packages/core
        run: pnpm build

      - name: Publish to npm (beta)
        working-directory: packages/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --tag beta

      - name: Create Beta GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
