name: Beta Release

on:
  push:
    tags:
      - 'v*-beta*' # z.B. v1.2.0-beta, v2.0.0-beta.1

jobs:
  beta-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Beta GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
